name: Filesystem Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest] # figure out execution on windows runner

    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake . -B build \
          -DBUILD_TESTS=ON \
          -DCMAKE_BUILD_TYPE=Debug 

    - name: Compile with configured bitmaps and indexing
      run: cmake --build build --verbose

    - name: Run Unit Tests
      run: cd build/test/ && ./test_object_table

